name: {{ cookiecutter.repo_name.lower().replace('_', '-').replace(' ', '-') }}-env
channels:
  - conda-forge
dependencies:
  - python={{ cookiecutter.python_version }}
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - libexpat=2.6.2
  - libffi=3.4.2
  - libsqlite=3.45.2
  - libzlib=1.2.13
  - openssl=3.2.1
  - pip=24.0
  - setuptools=69.2.0
  - tk=8.6.13
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - wheel=0.43.0
  - xz=5.2.6
  - pip:
      - asttokens==2.4.1
      - attrs==23.2.0
      - autopep8==2.1.0
      - bandit==1.7.8
      - beautifulsoup4==4.12.3
      - black==24.3.0
      - certifi==2024.2.2
      - cfgv==3.4.0
      - charset-normalizer==3.3.2
      - comm==0.2.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - debugpy==1.8.1
      - decorator==5.1.1
      - detect-secrets==1.4.0
      - distlib==0.3.8
      - et-xmlfile==1.1.0
      - executing==2.0.1
      - fastjsonschema==2.19.1
      - filelock==3.13.4
      - flake8==7.0.0
      - fonttools==4.51.0
      - identify==2.5.35
      - idna==3.6
      - ipykernel==6.29.4
      - ipython==8.23.0
      - isort==5.13.2
      - jedi==0.19.1
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.1
      - jupyter-core==5.7.2
      - kiwisolver==1.4.5
      - matplotlib==3.8.4
      - matplotlib-inline==0.1.6
      - mccabe==0.7.0
      - mypy-extensions==1.0.0
      - nbformat==5.10.4
      - nbqa==1.8.5
      - nbstripout==0.7.1
      - nest-asyncio==1.6.0
      - nodeenv==1.8.0
      - numpy==1.26.4
      - openpyxl==3.1.2
      - packaging==24.0
      - pandas==2.2.1
      - parso==0.8.4
      - pathspec==0.12.1
      - pbr==6.0.0
      - pillow==10.3.0
      - platformdirs==4.2.0
      - pre-commit==3.7.0
      - prompt-toolkit==3.0.43
      - psutil==5.9.8
      - pure-eval==0.2.2
      - pycodestyle==2.11.1
      - pyflakes==3.2.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2024.1
      - pywin32==306
      - pyzmq==25.1.2
      - referencing==0.34.0
      - requests==2.31.0
      - rpds-py==0.18.0
      - seaborn==0.13.2
      - six==1.16.0
      - soupsieve==2.5
      - stack-data==0.6.3
      - stevedore==5.2.0
      - tokenize-rt==5.2.0
      - tomli==2.0.1
      - tornado==6.4
      - traitlets==5.14.2
      - tzdata==2024.1
      - urllib3==2.2.1
      - virtualenv==20.25.1
      - wcwidth==0.2.13